# Generated by Django 5.2.15 on 2026-06-16 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_shape', models.CharField(default='circle', max_length=10)),
                ('border_color', models.CharField(default='#8083ff', max_length=7)),
                ('border_width', models.PositiveSmallIntegerField(default=2)),
                ('bg_type', models.CharField(default='color', max_length=10)),
                ('bg_color', models.CharField(default='#13131b', max_length=7)),
                ('bg_color2', models.CharField(default='#1f1f27', max_length=7)),
                ('bg_gradient_dir', models.CharField(default='to bottom', max_length=10)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('bg_video_url', models.URLField(blank=True, max_length=500)),
                ('btn_style', models.CharField(default='filled', max_length=10)),
                ('btn_color', models.CharField(default='#8083ff', max_length=7)),
                ('btn_text_color', models.CharField(default='#0d0096', max_length=7)),
                ('btn_radius', models.PositiveSmallIntegerField(default=12)),
                ('btn_hover', models.BooleanField(default=True)),
                ('font_family', models.CharField(default='Inter', max_length=60)),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('text_color', models.CharField(default='#e4e1ed', max_length=7)),
                ('social_icon_style', models.CharField(default='colorful', max_length=10)),
                ('social_icon_size', models.CharField(default='medium', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(default='link', max_length=40)),
                ('icon_type', models.CharField(default='material', max_length=20)),
                ('color', models.CharField(default='#8083ff', max_length=7)),
                ('display_style', models.CharField(default='icon_text', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
