# Generated by Django 5.2.15 on 2026-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appearance_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
