# Generated by Django 5.2.15 on 2026-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_link_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
