# Generated by Django 5.2.15 on 2026-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_link_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
